/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_front_end;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import static java.util.concurrent.TimeUnit.DAYS;



/**
 *
 * @author golde
 */
public class ReturnBookPage extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBookPage
     */
    boolean optionSelected = false;
    boolean initialised = false;
    int diff;
    
    MongoClient mongoClient = new MongoClient("192.168.1.11", 27017);
    //defines the ipaddress and port to use to connect
    DB db = mongoClient.getDB("Library");
    //defines the database to use
    DBCollection collection = db.getCollection("Members");
    //defines the collection to use
    
    public ReturnBookPage() {
        initComponents();
        comboPopulation();
        
        
        
    }
    
    public void setMoneyOwed(String date){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
        collection = db.getCollection("Orders");
        
        LocalDate today = LocalDate.now();
        LocalDate dateDue = LocalDate.parse(date, formatter);
        
        diff = dateDue.until(today).getDays();
        
        lblMoneyOwed.setText("You Owe: £" + diff);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberName = new javax.swing.JComboBox<>();
        bookName = new javax.swing.JComboBox<>();
        dateReturned = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReturnBook = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblMoneyOwed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        memberName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                memberNameItemStateChanged(evt);
            }
        });

        bookName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookNameItemStateChanged(evt);
            }
        });

        jLabel1.setText("Member Name");

        jLabel2.setText("Book Name");

        jLabel3.setText("Date Returned");

        btnReturnBook.setText("Return Book");
        btnReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnBookMouseClicked(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        lblMoneyOwed.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblMoneyOwed.setText("You Owe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(memberName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bookName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateReturned, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblMoneyOwed, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnReturnBook)
                        .addGap(51, 51, 51)
                        .addComponent(btnReset)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateReturned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addComponent(lblMoneyOwed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnBook)
                    .addComponent(btnReset))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnBookMouseClicked
        // TODO add your handling code here:
        String selectedBookName = (String) bookName.getSelectedItem();
        String selectedMemberName = (String) memberName.getSelectedItem();
        String returnDate = dateReturned.getText();
        
        ReturnBook returnbook = new ReturnBook();
        returnbook.returnBook(selectedBookName, selectedMemberName, returnDate, diff);

    }//GEN-LAST:event_btnReturnBookMouseClicked

    private void memberNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_memberNameItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED && optionSelected == false && initialised == true) {
        //Do any operations you need to do when an item is selected.

            collection = db.getCollection("Orders");
            //defines the collection to use
            DBCursor cursor = collection.find(
            new BasicDBObject(), new BasicDBObject("MemberName", Boolean.TRUE)
            );
        
            DBCursor cursor2 = collection.find(
            new BasicDBObject(), new BasicDBObject("BookName", Boolean.TRUE)
            );
            //uses a cursor to search the collection for all values in the BookName field
            DBCursor cursor3 = collection.find(
            new BasicDBObject(), new BasicDBObject("DateDue", Boolean.TRUE)
            );
            
            String b = (String)evt.getItem();
            String date = null;
            
            while (cursor.hasNext()) {
            
                String a = cursor.next().get("MemberName").toString();
                String c = cursor2.next().get("BookName").toString();
                date = cursor3.next().get("DateDue").toString();
            
                if(b.equals(a) && optionSelected == false){
                    optionSelected = true;
                    System.out.println("found match");
                    System.out.println(c);
                    bookName.removeAllItems();
                    bookName.addItem(c);
                    memberName.removeAllItems();
                    memberName.addItem(b);
                    setMoneyOwed(date);
                        
                }else if(b.equals(a)){
                    bookName.addItem(c);
                    setMoneyOwed(date);
                }
            }
            
            
        }
        
    }//GEN-LAST:event_memberNameItemStateChanged

    private void bookNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookNameItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED && initialised == true && optionSelected == false) {
        //Do any operations you need to do when an item is selected.
            optionSelected = true;

            collection = db.getCollection("Orders");
            //defines the collection to use
            DBCursor cursor = collection.find(
            new BasicDBObject(), new BasicDBObject("MemberName", Boolean.TRUE)
            );
        
            DBCursor cursor2 = collection.find(
            new BasicDBObject(), new BasicDBObject("BookName", Boolean.TRUE)
            );
            //uses a cursor to search the collection for all values in the catagory field
            DBCursor cursor3 = collection.find(
            new BasicDBObject(), new BasicDBObject("DateDue", Boolean.TRUE)
            );
            String b = (String)evt.getItem();
            String date = null;
            
            bookName.removeAllItems();
            bookName.addItem(b);
            
            while (cursor2.hasNext()) {

                String a = cursor2.next().get("BookName").toString();
                String c = cursor.next().get("MemberName").toString();
                date = cursor3.next().get("DateDue").toString();
            
                if(a.equals(b)){
                    System.out.println("found match");
                    System.out.println(c);
                
                    memberName.removeAllItems();
                    memberName.addItem(c);
                    setMoneyOwed(date);
   
                }
            }
            
        }
    }//GEN-LAST:event_bookNameItemStateChanged

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        memberName.removeAllItems();
        bookName.removeAllItems();
        comboPopulation();
        
    }//GEN-LAST:event_btnResetMouseClicked

    private void comboPopulation(){
        initialised = false;
        memberName.addItem("Choose a member");
        bookName.addItem("Choose a book");
        
        collection = db.getCollection("Members");
        
        DBCursor cursor = collection.find(
        new BasicDBObject(), new BasicDBObject("FirstName", Boolean.TRUE)
         );
        
        DBCursor cursor2 = collection.find(
        new BasicDBObject(), new BasicDBObject("SecondName", Boolean.TRUE)
         );
        
        //uses a cursor to search the collection for all values in the catagory field
        while (cursor.hasNext()) {
            String memname = (String) cursor.next().get("FirstName") + " " + cursor2.next().get("SecondName");
            memberName.addItem(memname);

    }

        collection = db.getCollection("Books");
        //defines the collection to use
        
        cursor = collection.find(
        new BasicDBObject(), new BasicDBObject("BookName", Boolean.TRUE)
         );
        //uses a cursor to search the collection for all values in the catagory field
        while (cursor.hasNext()) {
            bookName.addItem((String) cursor.next().get("BookName"));
        }
        //uses the cursor to populate the combo box bookName
        initialised = true;
        optionSelected = false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookName;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JTextField dateReturned;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMoneyOwed;
    private javax.swing.JComboBox<String> memberName;
    // End of variables declaration//GEN-END:variables
}